version: "3.9"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${KNEX_USERNAME}
      POSTGRES_PASSWORD: ${KNEX_PASSWORD}
      PGDATA: /data/postgres
      POSTGRES_DB: ${KNEX_DATABASE}
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres:
