/**
 * API Error Codes
 * These error codes help clients identify specific error types
 */
export const ErrorCodes = {
  // Validation Errors (4000-4099)
  VALIDATION_ERROR: 'ERR_VALIDATION_FAILED',
  INVALID_INPUT: 'ERR_INVALID_INPUT',
  MISSING_REQUIRED_FIELD: 'ERR_MISSING_REQUIRED_FIELD',
  INVALID_FORMAT: 'ERR_INVALID_FORMAT',

  // Authentication Errors (4010-4019)
  AUTHENTICATION_FAILED: 'ERR_AUTHENTICATION_FAILED',
  INVALID_CREDENTIALS: 'ERR_INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'ERR_TOKEN_EXPIRED',
  TOKEN_INVALID: 'ERR_TOKEN_INVALID',
  SESSION_EXPIRED: 'ERR_SESSION_EXPIRED',

  // Authorization Errors (4030-4039)
  FORBIDDEN: 'ERR_FORBIDDEN',
  INSUFFICIENT_PERMISSIONS: 'ERR_INSUFFICIENT_PERMISSIONS',
  ACCESS_DENIED: 'ERR_ACCESS_DENIED',

  // Not Found Errors (4040-4049)
  RESOURCE_NOT_FOUND: 'ERR_RESOURCE_NOT_FOUND',
  USER_NOT_FOUND: 'ERR_USER_NOT_FOUND',
  BOARD_NOT_FOUND: 'ERR_BOARD_NOT_FOUND',
  CARD_NOT_FOUND: 'ERR_CARD_NOT_FOUND',
  PROFILE_NOT_FOUND: 'ERR_PROFILE_NOT_FOUND',

  // Conflict Errors (4090-4099)
  RESOURCE_CONFLICT: 'ERR_RESOURCE_CONFLICT',
  DUPLICATE_RESOURCE: 'ERR_DUPLICATE_RESOURCE',
  USERNAME_ALREADY_EXISTS: 'ERR_USERNAME_ALREADY_EXISTS',
  EMAIL_ALREADY_EXISTS: 'ERR_EMAIL_ALREADY_EXISTS',

  // Rate Limiting (4290-4299)
  TOO_MANY_REQUESTS: 'ERR_TOO_MANY_REQUESTS',
  RATE_LIMIT_EXCEEDED: 'ERR_RATE_LIMIT_EXCEEDED',

  // Server Errors (5000-5099)
  INTERNAL_SERVER_ERROR: 'ERR_INTERNAL_SERVER_ERROR',
  DATABASE_ERROR: 'ERR_DATABASE_ERROR',
  SERVICE_UNAVAILABLE: 'ERR_SERVICE_UNAVAILABLE',
  EXTERNAL_API_ERROR: 'ERR_EXTERNAL_API_ERROR',
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];
