
services:

  app:
    container_name: app-sprinty
    build: .
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      - db
    command: node dist/app.js

  db:
    container_name: database-sprinty
    image: postgres
    environment:
      POSTGRES_USER: ${KNEX_USERNAME}
      POSTGRES_PASSWORD: ${KNEX_PASSWORD}
      PGDATA: /data/postgres
      POSTGRES_DB: ${KNEX_DATABASE}
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prometheus-sprinty
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prom/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana-sprinty
    restart: unless-stopped
    ports:
      - "3030:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

  cache:
    container_name: cache-sprinty
    image: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - cache:/data

volumes:
  postgres:
  prom_data:
  grafana-storage: {}
  cache:
    driver: local

